--liquibase formatted sql

--changeset kmpk:init_schema
DROP TABLE IF EXISTS USER_ROLE;
DROP TABLE IF EXISTS CONTACT;
DROP TABLE IF EXISTS MAIL_CASE;
DROP TABLE IF EXISTS PROFILE;
DROP TABLE IF EXISTS TASK_TAG;
DROP TABLE IF EXISTS USER_BELONG;
DROP TABLE IF EXISTS ACTIVITY;
DROP TABLE IF EXISTS TASK;
DROP TABLE IF EXISTS SPRINT;
DROP TABLE IF EXISTS PROJECT;
DROP TABLE IF EXISTS REFERENCE;
DROP TABLE IF EXISTS ATTACHMENT;
DROP TABLE IF EXISTS USERS;

CREATE TABLE PROJECT (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CODE VARCHAR(32) NOT NULL,
    TITLE VARCHAR(1024) NOT NULL,
    DESCRIPTION VARCHAR(4096) NOT NULL,
    TYPE_CODE VARCHAR(32) NOT NULL,
    STARTPOINT TIMESTAMP,
    ENDPOINT TIMESTAMP,
    PARENT_ID BIGINT,
    CONSTRAINT UK_PROJECT_CODE UNIQUE (CODE),
    CONSTRAINT FK_PROJECT_PARENT FOREIGN KEY (PARENT_ID) REFERENCES PROJECT (ID) ON DELETE CASCADE
);

create table MAIL_CASE
(
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EMAIL     VARCHAR(255) not null,
    NAME      VARCHAR(255) not null,
    DATE_TIME TIMESTAMP    not null,
    RESULT    VARCHAR(255) not null,
    TEMPLATE  VARCHAR(255) not null
);

CREATE TABLE SPRINT (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    STATUS_CODE VARCHAR(32) NOT NULL,
    STARTPOINT  TIMESTAMP,
    ENDPOINT    TIMESTAMP,
    TITLE       VARCHAR(1024) NOT NULL,
    PROJECT_ID  BIGINT NOT NULL,
    CONSTRAINT FK_SPRINT_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (ID) ON DELETE CASCADE
);

CREATE TABLE REFERENCE (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CODE       VARCHAR(32)   NOT NULL,
    REF_TYPE   SMALLINT      NOT NULL,
    ENDPOINT   TIMESTAMP,
    STARTPOINT TIMESTAMP,
    TITLE      VARCHAR(1024) NOT NULL,
    AUX        VARCHAR,
    CONSTRAINT UK_REFERENCE_REF_TYPE_CODE UNIQUE (REF_TYPE, CODE)
);

CREATE TABLE USERS (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DISPLAY_NAME VARCHAR(32)  NOT NULL
        CONSTRAINT UK_USERS_DISPLAY_NAME UNIQUE,
    EMAIL        VARCHAR(128) NOT NULL
        CONSTRAINT UK_USERS_EMAIL UNIQUE,
    FIRST_NAME   VARCHAR(32)  NOT NULL,
    LAST_NAME    VARCHAR(32),
    PASSWORD     VARCHAR(128) NOT NULL,
    ENDPOINT     TIMESTAMP,
    STARTPOINT   TIMESTAMP
);

CREATE TABLE PROFILE (
    ID                 BIGINT PRIMARY KEY,
    LAST_LOGIN         TIMESTAMP,
    LAST_FAILED_LOGIN  TIMESTAMP,
    MAIL_NOTIFICATIONS BIGINT,
    CONSTRAINT FK_PROFILE_USERS FOREIGN KEY (ID) REFERENCES USERS (ID) ON DELETE CASCADE
);

CREATE TABLE CONTACT (
    ID    BIGINT       NOT NULL,
    CODE  VARCHAR(32)  NOT NULL,
    "VALUE" VARCHAR(256) NOT NULL,
    PRIMARY KEY (ID, CODE),
    CONSTRAINT FK_CONTACT_PROFILE FOREIGN KEY (ID) REFERENCES PROFILE (ID) ON DELETE CASCADE
);

CREATE TABLE TASK (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TITLE         VARCHAR(1024) NOT NULL,
    DESCRIPTION   VARCHAR(4096) NOT NULL,
    TYPE_CODE     VARCHAR(32)   NOT NULL,
    STATUS_CODE   VARCHAR(32)   NOT NULL,
    PRIORITY_CODE VARCHAR(32)   NOT NULL,
    ESTIMATE      INTEGER,
    UPDATED       TIMESTAMP,
    PROJECT_ID    BIGINT        NOT NULL,
    SPRINT_ID     BIGINT,
    PARENT_ID     BIGINT,
    STARTPOINT    TIMESTAMP,
    ENDPOINT      TIMESTAMP,
    CONSTRAINT FK_TASK_SPRINT FOREIGN KEY (SPRINT_ID) REFERENCES SPRINT (ID) ON DELETE SET NULL,
    CONSTRAINT FK_TASK_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (ID) ON DELETE CASCADE,
    CONSTRAINT FK_TASK_PARENT_TASK FOREIGN KEY (PARENT_ID) REFERENCES TASK (ID) ON DELETE CASCADE
);

CREATE TABLE ACTIVITY (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AUTHOR_ID     BIGINT NOT NULL,
    TASK_ID       BIGINT NOT NULL,
    UPDATED       TIMESTAMP,
    COMMENT       VARCHAR(4096),
    TITLE         VARCHAR(1024),
    DESCRIPTION   VARCHAR(4096),
    ESTIMATE      INTEGER,
    TYPE_CODE     VARCHAR(32),
    STATUS_CODE   VARCHAR(32),
    PRIORITY_CODE VARCHAR(32),
    CONSTRAINT FK_ACTIVITY_USERS FOREIGN KEY (AUTHOR_ID) REFERENCES USERS (ID),
    CONSTRAINT FK_ACTIVITY_TASK FOREIGN KEY (TASK_ID) REFERENCES TASK (ID) ON DELETE CASCADE
);

create table TASK_TAG
(
    TASK_ID bigint      not null,
    TAG     varchar(32) not null,
    constraint UK_TASK_TAG unique (TASK_ID, TAG),
    constraint FK_TASK_TAG foreign key (TASK_ID) references TASK (ID) on delete cascade
);

CREATE TABLE USER_BELONG (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OBJECT_ID      BIGINT      NOT NULL,
    OBJECT_TYPE    SMALLINT    NOT NULL,
    USER_ID        BIGINT      NOT NULL,
    USER_TYPE_CODE VARCHAR(32) NOT NULL,
    STARTPOINT     TIMESTAMP,
    ENDPOINT       TIMESTAMP,
    CONSTRAINT FK_USER_BELONG FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);
-- create unique index UK_USER_BELONG on USER_BELONG (OBJECT_ID, OBJECT_TYPE, USER_ID, USER_TYPE_CODE);
create index IX_USER_BELONG_USER_ID on USER_BELONG (USER_ID);

CREATE TABLE ATTACHMENT (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME        VARCHAR(128)  NOT NULL,
    FILE_LINK   VARCHAR(2048) NOT NULL,
    OBJECT_ID   BIGINT        NOT NULL,
    OBJECT_TYPE SMALLINT      NOT NULL,
    USER_ID     BIGINT        NOT NULL,
    DATE_TIME   TIMESTAMP,
    CONSTRAINT FK_ATTACHMENT FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

CREATE TABLE USER_ROLE (
    USER_ID BIGINT   NOT NULL,
    ROLE    SMALLINT NOT NULL,
    CONSTRAINT UK_USER_ROLE UNIQUE (USER_ID, ROLE),
    CONSTRAINT FK_USER_ROLE FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE
);

--changeset kmpk:populate_data
--============ References =================
insert into REFERENCE (CODE, TITLE, REF_TYPE)
-- TASK
values ('task', 'Task', 2),
       ('story', 'Story', 2),
       ('bug', 'Bug', 2),
       ('epic', 'Epic', 2),
-- SPRINT_STATUS
       ('planning', 'Planning', 4),
       ('active', 'Active', 4),
       ('finished', 'Finished', 4),
-- USER_TYPE
       ('author', 'Author', 5),
       ('developer', 'Developer', 5),
       ('reviewer', 'Reviewer', 5),
       ('tester', 'Tester', 5),
-- PROJECT
       ('scrum', 'Scrum', 1),
       ('task_tracker', 'Task tracker', 1),
-- CONTACT
       ('skype', 'Skype', 0),
       ('tg', 'Telegram', 0),
       ('mobile', 'Mobile', 0),
       ('phone', 'Phone', 0),
       ('website', 'Website', 0),
       ('linkedin', 'LinkedIn', 0),
       ('github', 'GitHub', 0),
-- PRIORITY
       ('critical', 'Critical', 7),
       ('high', 'High', 7),
       ('normal', 'Normal', 7),
       ('low', 'Low', 7),
       ('neutral', 'Neutral', 7);

insert into REFERENCE (CODE, TITLE, REF_TYPE, AUX)
-- MAIL_NOTIFICATION
values ('assigned', 'Assigned', 6, '1'),
       ('three_days_before_deadline', 'Three days before deadline', 6, '2'),
       ('two_days_before_deadline', 'Two days before deadline', 6, '4'),
       ('one_day_before_deadline', 'One day before deadline', 6, '8'),
       ('deadline', 'Deadline', 6, '16'),
       ('overdue', 'Overdue', 6, '32'),
-- TASK_STATUS
       ('todo', 'ToDo', 3, 'in_progress,canceled'),
       ('in_progress', 'In progress', 3, 'ready_for_review,canceled'),
       ('ready_for_review', 'Ready for review', 3, 'review,canceled'),
       ('review', 'Review', 3, 'in_progress,ready_for_test,canceled'),
       ('ready_for_test', 'Ready for test', 3, 'test,canceled'),
       ('test', 'Test', 3, 'done,in_progress,canceled'),
       ('done', 'Done', 3, 'canceled'),
       ('canceled', 'Canceled', 3, null);

--changeset gkislin:change_backtracking_tables

alter table SPRINT rename COLUMN TITLE to CODE;
alter table SPRINT
    alter column CODE type varchar (32);
alter table SPRINT
    alter column CODE set not null;
create unique index UK_SPRINT_PROJECT_CODE on SPRINT (PROJECT_ID, CODE);

ALTER TABLE TASK
    DROP COLUMN DESCRIPTION;
ALTER TABLE TASK
    DROP COLUMN PRIORITY_CODE;
ALTER TABLE TASK
    DROP COLUMN ESTIMATE;
ALTER TABLE TASK
    DROP COLUMN UPDATED;

--changeset ishlyakhtenkov:change_task_status_reference

delete
from REFERENCE
where REF_TYPE = 3;
insert into REFERENCE (CODE, TITLE, REF_TYPE, AUX)
values ('todo', 'ToDo', 3, 'in_progress,canceled'),
       ('in_progress', 'In progress', 3, 'ready_for_review,canceled'),
       ('ready_for_review', 'Ready for review', 3, 'in_progress,review,canceled'),
       ('review', 'Review', 3, 'in_progress,ready_for_test,canceled'),
       ('ready_for_test', 'Ready for test', 3, 'review,test,canceled'),
       ('test', 'Test', 3, 'done,in_progress,canceled'),
       ('done', 'Done', 3, 'canceled'),
       ('canceled', 'Canceled', 3, null);

--changeset gkislin:users_add_on_delete_cascade

-- Для ACTIVITY
ALTER TABLE ACTIVITY
    DROP CONSTRAINT FK_ACTIVITY_USERS;
ALTER TABLE ACTIVITY
    ADD CONSTRAINT FK_ACTIVITY_USERS FOREIGN KEY (AUTHOR_ID) REFERENCES USERS (ID) ON DELETE CASCADE;

-- Для USER_BELONG
ALTER TABLE USER_BELONG
    DROP CONSTRAINT FK_USER_BELONG;
ALTER TABLE USER_BELONG
    ADD CONSTRAINT FK_USER_BELONG FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE;

-- Для ATTACHMENT
ALTER TABLE ATTACHMENT
    DROP CONSTRAINT FK_ATTACHMENT;
ALTER TABLE ATTACHMENT
    ADD CONSTRAINT FK_ATTACHMENT FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE;
--changeset valeriyemelyanov:change_user_type_reference

delete
from REFERENCE
where REF_TYPE = 5;
insert into REFERENCE (CODE, TITLE, REF_TYPE)
-- USER_TYPE
values ('project_author', 'Author', 5),
       ('project_manager', 'Manager', 5),
       ('sprint_author', 'Author', 5),
       ('sprint_manager', 'Manager', 5),
       ('task_author', 'Author', 5),
       ('task_developer', 'Developer', 5),
       ('task_reviewer', 'Reviewer', 5),
       ('task_tester', 'Tester', 5);

--changeset apolik:refactor_reference_aux

-- TASK_TYPE
delete
from REFERENCE
where REF_TYPE = 3;
insert into REFERENCE (CODE, TITLE, REF_TYPE, AUX)
values ('todo', 'ToDo', 3, 'in_progress,canceled|'),
       ('in_progress', 'In progress', 3, 'ready_for_review,canceled|task_developer'),
       ('ready_for_review', 'Ready for review', 3, 'in_progress,review,canceled|'),
       ('review', 'Review', 3, 'in_progress,ready_for_test,canceled|task_reviewer'),
       ('ready_for_test', 'Ready for test', 3, 'review,test,canceled|'),
       ('test', 'Test', 3, 'done,in_progress,canceled|task_tester'),
       ('done', 'Done', 3, 'canceled|'),
       ('canceled', 'Canceled', 3, null);

